version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - "27117:27017"
    #    volumes:
    #      - ./mongo/data/db:/data/db
  server:
    build: ./server
    ports:
      - "4001:4001"
    environment:
      - MONGO=mongodb://mongo:27017
    links:
      - mongo:mongo
  web:
    build:
      context: ./web
      args:
        REACT_APP_API_URL: http://192.168.43.211:4000/graphql
        REACT_APP_WEBSOCKET_URL: ws://192.168.43.211:4000/graphql
        REACT_APP_XREAD_URL: http://192.168.43.211:4000/
  nginx:
    build: ./nginx
    links:
      - server:server
      - web:web
    ports:
      - "5000:80"